// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeYmvnMiJouQ_UJZLhtmvs3Qjiq8D7RvM',
    appId: '1:1085054651658:web:cc2a7f93f877e900c23ef3',
    messagingSenderId: '1085054651658',
    projectId: 'purvi-vogue',
    authDomain: 'purvi-vogue.firebaseapp.com',
    storageBucket: 'purvi-vogue.firebasestorage.app',
    measurementId: 'G-0NE0CWMRBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOO3DM17-qi1rYxBYnjLD3fdNDqPrybg',
    appId: '1:1085054651658:android:9f9b9dcabcaac243c23ef3',
    messagingSenderId: '1085054651658',
    projectId: 'purvi-vogue',
    storageBucket: 'purvi-vogue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cgUc1JrbwzbVtcC_67kexeIjTju7p3k',
    appId: '1:1085054651658:ios:9cd8f9896eba7581c23ef3',
    messagingSenderId: '1085054651658',
    projectId: 'purvi-vogue',
    storageBucket: 'purvi-vogue.firebasestorage.app',
    iosBundleId: 'com.example.purviVogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cgUc1JrbwzbVtcC_67kexeIjTju7p3k',
    appId: '1:1085054651658:ios:9cd8f9896eba7581c23ef3',
    messagingSenderId: '1085054651658',
    projectId: 'purvi-vogue',
    storageBucket: 'purvi-vogue.firebasestorage.app',
    iosBundleId: 'com.example.purviVogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeYmvnMiJouQ_UJZLhtmvs3Qjiq8D7RvM',
    appId: '1:1085054651658:web:4a823dc74f607bdcc23ef3',
    messagingSenderId: '1085054651658',
    projectId: 'purvi-vogue',
    authDomain: 'purvi-vogue.firebaseapp.com',
    storageBucket: 'purvi-vogue.firebasestorage.app',
    measurementId: 'G-PD6RS5NJSV',
  );
}
